/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'omid' at '11/1/16 10:35 PM' with Gradle 2.13
 *
 * @author omid, @date 11/1/16 10:35 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
