/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'omid' at '11/1/16 10:35 PM' with Gradle 2.13
 *
 * @author omid, @date 11/1/16 10:35 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
